export const Levels = ["Easy", "Medium", "Hard", "Expert"];
// export const Joints = [
//   "leftShoulder",
//   "rightShoulder",
//   "leftElbow",
//   "rightElbow",
//   "leftWrist",
//   "rightWrist",
//   "leftHip",
//   "rightHip",
//   "leftKnee",
//   "rightKnee",
//   "leftAnkle",
//   "rightAnkle",
//   "neck",
//   "pelvic",
// ];
export const Joints = [
  { name: "Cervical", value: "leftNeck" },
  { name: "Shoulder", value: "leftShoulder" },
  { name: "Hip", value: "leftHip" },
  { name: "Pelvic", value: "leftPelvic" },
  { name: "Knee", value: "leftKnee" },
  { name: "Ankle", value: "leftAnkle" },
  { name: "Elbow", value: "leftElbow" },
  { name: "Wrist", value: "leftWrist" },
];
export const Muscles = [
  "Abdominals",
  "Backtraps",
  "Biceps",
  "Calves",
  "Foot & Shin",
  "Glutes",
  "Groin - Hip",
  "Hamstrings",
  "LowerBack",
  "Pecs",
  "Quads",
  "Rotator Cuff",
  "Scapula",
  "Traps",
  "Triceps",
  "Wrist - Hand",
];
export const Movement = [
  "Abduction",
  "Adduction",
  "Extension",
  "Rotation",
  "Flexion",
  "Protraction",
  "Retraction",
];
